# Generated by Django 6.0 on 2026-01-19 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('open_ports', models.JSONField(default=list)),
                ('os_info', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Completed', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='scanner.networkdevice')),
            ],
        ),
    ]
